version: '3'


services:
 backend:
   build:
     context: .
     dockerfile: ./hadiya-back/Dockerfile
   image: node-build


 nginx:
   image: nginx:latest
   container_name: my-backend-nginx-container 
   volumes:
     - ./hadiya-back/conf.d:/etc/nginx/conf.d
   depends_on:
     - backend
   ports:
     - "3000:3000"
   networks:
     - internalnet
networks:
 internalnet:
   driver: bridge
